---

- name: Load variables based on OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "family-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "family-{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - "vars"

- name: Install nginx packages
  ansible.builtin.package:
    name: "{{ nginx_packages }}"
    state: present

- name: Create default server configuration
  template:
    src: default.conf.j2
    dest: "{{ nginx_confd_path }}/default.conf"
    owner: root
    group: root
    mode: "0644"
    force: false
  notify: Restart nginx
  when:
    - ansible_os_family == 'Debian'
    - nginx_default_server|bool

- name: Create all vhosts
  include_tasks: vhost.yml
  loop: "{{ nginx_confd_templates }}"
  loop_control:
    loop_var: nginx_vhost
  when: nginx_create_vhosts|bool
    
- name: Let nginx contact network resources
  ansible.posix.seboolean:
    name: "{{ item }}"
    persistent: yes
    state: yes
  loop:
    - httpd_can_network_connect
    - httpd_can_network_relay
  when:
    - ansible_os_family == 'RedHat'
    - ansible_selinux['status'] == 'enabled'

- name: Remove link to 'sites-enabled/default'
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Configuring firewall for postfix (ports)
  include_role:
    name: firewall
  vars:
    firewall_ports: "{{ nginx_fw_ports }}"
  when: nginx_manage_firewall|bool
